### ISSUE TITLE
Flourescene signal plot gives negative values

### ISSUE THREAD

**Issue by BrianNGitahi** [BrianNGitahi/NM-Imaging#1]
Section 3:
I'm not sure whether it's just the constants I plugged in that are the error
-- could be a symptom of a bigger problem further down

**Comment by hagikent** [comment]
I see two points to be updated

1. We should first calculate F, and then calculate dF/F0. F0 estimation part seems to be overlooked?

2. the following statement looks wrong: "The fluorescence when sensor is completely unbound to NM, F_max"
Based on the Neher/Augustine, F_max should be the F of sensor **with** complete NM-bound. And F_min is the F of sensor w/o NM. This is because virtually all the NM sensors (actually there are few exception) we use are "positive sensors" that increase their fluorescence intensity when NM bounded.

**Comment by BrianNGitahi** [comment]
1. There was no direct calculation of F in the paper; from what I saw it looked like it wasn't necessary to directly calculate F or F0 -- I could be wrong tho
2. Then for Fmax and Fmin I guess it's just the negative/positive sensor issue we discussed -- just rewriting it here for future reference

**Comment by hagikent** [comment]
<img width="741" alt="Screen Shot 2023-09-27 at 10 07 13" src="https://github.com/BrianNGitahi/NM-Imaging/assets/54397345/67c3bb80-cd98-47d9-a5ba-707b5f74075e">
In the Neher/Augustine, Fura-2 is used as a negative sensor (>350nm)
(Just for posterity)
